routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
 * Login & Registration Routes
 */

Auth::routes(['verify' => true]);
Route::get('signup', 'SignupController@signup');
Route::post('signup', 'SignupController@register')->name('signup');
Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));
Route::get('{driver}/callback', 'Auth\LoginController@handleProviderCallback')
    ->name('login.callback')
    ->where('driver', implode('|', config('auth.socialite.drivers')));

/*
 * Default users Routes
 */
Route::get('/', 'Frontend\FrontEndController@index')->name('user.index');
Route::post('subscription', 'Frontend\FrontEndController@subscription')->name('frontend.subscription');
Route::get('search', 'SearchController@search')->name('search');
Route::get('location', 'SearchController@set_location')->name('location');
Route::get('search_cities', 'SearchController@search')->name('search_cities');
Route::get('all_cities', 'Frontend\FrontEndController@all_cities');
Route::get('faq', 'Frontend\FrontEndController@faq');
Route::get('terms_conditions', 'Frontend\FrontEndController@terms_conditions');
Route::get('privacy_policy', 'Frontend\FrontEndController@privacy_policy');
Route::get('list-business/{slug}', 'Frontend\BusinessController@index');
Route::get('user/{slug}', 'Frontend\ProfileController@index');
Route::get('autocomplete_locations', 'SearchController@autocomplete_locations')->name('autocomplete_locations');
Route::get('autocomplete_keyword', 'SearchController@autocomplete_keyword')->name('autocomplete_keyword');
Route::get('autocomplete_business', 'SearchController@autocomplete_business')->name('autocomplete_business');
Route::get('autocomplete_city', 'SearchController@autocomplete_city')->name('autocomplete_city');
Route::get('autocomplete_town', 'SearchController@autocomplete_town')->name('autocomplete_town');
Route::get('list_cities', 'SearchController@list_cities')->name('list_cities');
Route::group(['middleware' => ['check_business_role', 'check_admin_role']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('write_a_review', 'DefaultUser\ReviewController@writeareview')->name('search.business');
    Route::get('write_a_review/{slug}', 'DefaultUser\ReviewController@write_a_review_page')->name('write_a_review_store');
    Route::post('store_review', 'DefaultUser\ReviewController@postReview')->name('user.store.review');
    Route::post('/my/business/store', 'DefaultUser\BusinessController@store_business')->name('user.business.store');
    Route::get('/my/business/create', 'DefaultUser\BusinessController@create');
    Route::get('my/reviews', 'DefaultUser\ReviewController@index')->name('user.reviews');
    Route::get('my/profile', 'UserProfileController@index')->name('user.profile');
    Route::get('setting', 'DefaultUser\ProfileController@setting')->name('user.profile');
    Route::get('claim_business/{slug}', 'DefaultUser\BusinessController@claim_business')->name('user.claim_business');
    Route::post('store_claim_business', 'DefaultUser\BusinessController@store_claim_business')->name('user.store_claim_business');
});


/*
 * Business Routes
 */



Route::prefix('business')->group(function () {
    Route::group(['middleware' => ['check_admin_role', 'role:business']], function () {
        Route::get('/', 'BusinessUser\BusinessController@index')->name('individual.business.index');
        Route::get('setting', 'BusinessUser\BusinessController@setting');
        Route::get('business/reviews', 'BusinessUser\BusinessController@index');
    });
});


/*
 * Admin Routes
 */

Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/', 'AdminController@index')->name('admin.index');
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('business', 'AdminUser\BusinessController');
        Route::resource('business_category', 'AdminUser\BusinessCategoryController');
        Route::resource('city', 'AdminUser\CityController');
        Route::resource('town', 'AdminUser\TownController');
        Route::resource('claims', 'AdminUser\BusinessClaimController');
        Route::post('verify_business', 'AdminUser\BusinessController@verify_business')->name('verify_business');
        Route::post('claim_business', 'AdminUser\BusinessClaimController@claim_business')->name('admin.claim_business');
        Route::resource('subscription', 'AdminUser\SubscriptionController');
    });
});


Route::get('email-verify', function () {
    dd(Auth::user()->sendEmailVerificationNotification());
});




/**
 * Testing
 */
Route::get('google-maps', function () {
    return view('test.search');
});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = ['name'];
    public function business()
    {
        return $this->belongsToMany('App\Business');
    }

    public function towns()
    {
        return $this->hasMany('App\Town');
    }
}

app/Http/Controllers/AdminUser/CityController.php
<?php

namespace App\Http\Controllers\AdminUser;

use App\City;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities = City::all();
        return view('admin.city.index', compact('cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.city.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $input = $request->all();
      
        $city = City::create($input);
        
        return redirect()->route('city.index')
            ->with('success','City created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
     
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $city = City::findOrFail($id);
        return view('admin.city.edit',compact('city'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $city = City::find($id);
        $input = $request->all();

        $city->update($input);
       
        return redirect()->back()
            ->with('success','City updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        City::find($id)->delete();
        return redirect()->back()->with('success','City deleted successfully');
    }
}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\City;
use Illuminate\Http\Request;

class CityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, City $city)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city)
    {
        //
    }
}

resources/views/admin/city/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">

            <!-- Header -->
            <div class="header mt-md-5">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">

                            <!-- Pretitle -->
                            <h6 class="header-pretitle">
                                New City
                            </h6>

                            <!-- Title -->
                            <h1 class="header-title">
                                Create a new City
                            </h1>

                        </div>
                    </div> <!-- / .row -->
                </div>
            </div>
             @if(Session::has('success'))
             <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
             @endif
             @if(Session::has('error'))
             <p class="alert {{ Session::get('alert-class', 'alert-danger') }}">{{ Session::get('error') }}</p>
             @endif

            <!-- Form -->
            <form class="mb-4" method="POST" action="{{route('city.store')}}" enctype="multipart/form-data">

            @csrf
                <!-- Project name -->
                <div class="form-group">

                    <!-- Label  -->
                    <label>
                        City name
                    </label>

                    <!-- Input -->
                    <input type="text" name="name" class="form-control">

                </div>
                <!-- Project name -->
         
                <!-- Divider -->
                <hr class="mt-5 mb-5">

                <!-- Buttons -->
                <input type="submit" name="submit" value="Create City" class="btn btn-block btn-primary">

                {{-- <a href="#" class="btn btn-block btn-primary">
                    Create project
                </a> --}}
                <a href="{{route('city.index')}}" class="btn btn-block btn-link text-muted">

                    Cancel this City
                </a>

            </form>

        </div>
    </div> <!-- / .row -->
</div>

@endsection

resources/views/admin/city/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">

            <!-- Header -->
            <div class="header mt-md-5">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">

                            <!-- Pretitle -->
                            <h6 class="header-pretitle">
                                 City
                            </h6>

                            <!-- Title -->
                            <h1 class="header-title">
                               Update City
                            </h1>

                        </div>
                    </div> <!-- / .row -->
                </div>
            </div>
            @if(Session::has('success'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
            @endif
            @if(Session::has('error'))
            <p class="alert {{ Session::get('alert-class', 'alert-danger') }}">{{ Session::get('error') }}</p>
            @endif

            <!-- Form -->
            <form role="form" action="{{route('city.update',$city->id)}}" method="POST" >
                <input type="hidden" name="_method" value="PUT">
                @csrf

                <!-- Project name -->
                <div class="form-group">

                    <!-- Label  -->
                    <label>
                        City name
                    </label>

                    <!-- Input -->
                    <input type="text" name="name" value="{{$city->name}}" class="form-control">

                </div>

                <!-- Divider -->
                <hr class="mt-5 mb-5">

                <!-- Buttons -->
                <input type="submit" name="submit" value="Update Category" class="btn btn-block btn-primary">

                {{-- <a href="#" class="btn btn-block btn-primary">
                    Create project
                </a> --}}
                <a href="{{route('city.index')}}" class="btn btn-block btn-link text-muted">
                    Cancel this Category
                </a>

            </form>

        </div>
    </div> <!-- / .row -->
</div>

@endsection

resources/views/admin/city/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container-fluid">
        <div class="header">
            <div class="container-fluid">

                <!-- Body -->
                <div class="header-body">
                    <div class="row align-items-end">
                        <div class="col">

                            <!-- Pretitle -->
                            <h6 class="header-pretitle">
                                Overview
                            </h6>

                            <!-- Title -->
                            <h1 class="header-title">
                                Cities
                            </h1>

                        </div>
                        <div class="col-auto">

                            <!-- Button -->
                            <a href="{{route('city.create')}}" class="btn btn-primary lift">
                                Create New City
                            </a>

                        </div>
                    </div> <!-- / .row -->
                </div> <!-- / .header-body -->

            </div>
        </div>
        @if(Session::has('success'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('success') }}</p>
        @endif
        @if(Session::has('error'))
            <p class="alert {{ Session::get('alert-class', 'alert-danger') }}">{{ Session::get('error') }}</p>
        @endif

        <div class="card">
            <div class="card-body">

                <!-- Table -->
                <div class="table-responsive">
                    <table class="table table-sm table-nowrap card-table text-secondary">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($cities as $key =>  $item)
                            <tr>
                                <td>{{ $key }}</td>
                                <td>{{ $item->name }}</td>
                                <td>
                                    <a href="{{route('city.edit', $item->id)}}"
                                       class="btn btn-warning btn-sm lift"><i class="fe fe-edit"></i></a>
                                    <form action="{{ route('city.destroy', $item->id)}}" method="post"
                                          class="d-inline-block">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-sm lift   " type="submit"><i class="fe fe-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection