routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
 * Login & Registration Routes
 */

Auth::routes(['verify' => true]);
Route::get('signup', 'SignupController@signup');
Route::post('signup', 'SignupController@register')->name('signup');
Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')
    ->name('login.provider')
    ->where('driver', implode('|', config('auth.socialite.drivers')));
Route::get('{driver}/callback', 'Auth\LoginController@handleProviderCallback')
    ->name('login.callback')
    ->where('driver', implode('|', config('auth.socialite.drivers')));

/*
 * Default users Routes
 */
Route::get('/', 'Frontend\FrontEndController@index')->name('user.index');
Route::post('subscription', 'Frontend\FrontEndController@subscription')->name('frontend.subscription');
Route::get('search', 'SearchController@search')->name('search');
Route::get('location', 'SearchController@set_location')->name('location');
Route::get('search_cities', 'SearchController@search')->name('search_cities');
Route::get('all_cities', 'Frontend\FrontEndController@all_cities');
Route::get('faq', 'Frontend\FrontEndController@faq');
Route::get('terms_conditions', 'Frontend\FrontEndController@terms_conditions');
Route::get('privacy_policy', 'Frontend\FrontEndController@privacy_policy');
Route::get('list-business/{slug}', 'Frontend\BusinessController@index');
Route::get('user/{slug}', 'Frontend\ProfileController@index');
Route::get('autocomplete_locations', 'SearchController@autocomplete_locations')->name('autocomplete_locations');
Route::get('autocomplete_keyword', 'SearchController@autocomplete_keyword')->name('autocomplete_keyword');
Route::get('autocomplete_business', 'SearchController@autocomplete_business')->name('autocomplete_business');
Route::get('autocomplete_city', 'SearchController@autocomplete_city')->name('autocomplete_city');
Route::get('autocomplete_town', 'SearchController@autocomplete_town')->name('autocomplete_town');
Route::get('list_cities', 'SearchController@list_cities')->name('list_cities');
Route::group(['middleware' => ['check_business_role', 'check_admin_role']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('write_a_review', 'DefaultUser\ReviewController@writeareview')->name('search.business');
    Route::get('write_a_review/{slug}', 'DefaultUser\ReviewController@write_a_review_page')->name('write_a_review_store');
    Route::post('store_review', 'DefaultUser\ReviewController@postReview')->name('user.store.review');
    Route::post('/my/business/store', 'DefaultUser\BusinessController@store_business')->name('user.business.store');
    Route::get('/my/business/create', 'DefaultUser\BusinessController@create');
    Route::get('my/reviews', 'DefaultUser\ReviewController@index')->name('user.reviews');
    Route::get('my/profile', 'UserProfileController@index')->name('user.profile');
    Route::get('setting', 'DefaultUser\ProfileController@setting')->name('user.profile');
    Route::get('claim_business/{slug}', 'DefaultUser\BusinessController@claim_business')->name('user.claim_business');
    Route::post('store_claim_business', 'DefaultUser\BusinessController@store_claim_business')->name('user.store_claim_business');
});


/*
 * Business Routes
 */



Route::prefix('business')->group(function () {
    Route::group(['middleware' => ['check_admin_role', 'role:business']], function () {
        Route::get('/', 'BusinessUser\BusinessController@index')->name('individual.business.index');
        Route::get('setting', 'BusinessUser\BusinessController@setting');
        Route::get('business/reviews', 'BusinessUser\BusinessController@index');
    });
});


/*
 * Admin Routes
 */

Route::prefix('admin')->group(function () {
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('/', 'AdminController@index')->name('admin.index');
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('permissions', 'PermissionController');
        Route::resource('business', 'AdminUser\BusinessController');
        Route::resource('business_category', 'AdminUser\BusinessCategoryController');
        Route::resource('city', 'AdminUser\CityController');
        Route::resource('town', 'AdminUser\TownController');
        Route::resource('claims', 'AdminUser\BusinessClaimController');
        Route::post('verify_business', 'AdminUser\BusinessController@verify_business')->name('verify_business');
        Route::post('claim_business', 'AdminUser\BusinessClaimController@claim_business')->name('admin.claim_business');
        Route::resource('subscription', 'AdminUser\SubscriptionController');
    });
});


Route::get('email-verify', function () {
    dd(Auth::user()->sendEmailVerificationNotification());
});




/**
 * Testing
 */
Route::get('google-maps', function () {
    return view('test.search');
});

resources/views/admin/partials/head.blade.php
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="AreasGH - Restaurants, Dentists, Bars, Beauty Salons, Doctors" />

    <!-- Libs CSS -->

    <link rel="stylesheet" href="{{ URL::asset('backend/assets/fonts/feather/feather.css') }}" />
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/fonts/fontawesome/css/all.min.css') }}" />
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/libs/flatpickr/dist/flatpickr.min.css') }}" />
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/libs/quill/dist/quill.core.css') }}" />
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/libs/image-upload/image-uploader.min.css') }}" />
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/libs/highlightjs/styles/vs2015.css') }}" />


    <!-- Theme CSS -->
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/css/theme.min.css') }}" id="stylesheetLight">
    <link rel="stylesheet" href="{{ URL::asset('backend/assets/css/theme-dark.min.css') }}" id="stylesheetDark">


    <style>
        body {
            display: none;
        }

    </style>

    <!-- Title -->
    <title>{{ config('app.name', 'AreasGH - Restaurants, Dentists, Bars, Beauty Salons, Doctors') }}</title>


</head>

resources/views/admin/partials/scripts.blade.php
 <script src="{{ URL::asset('backend/assets/libs/jquery/dist/jquery.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/%40shopify/draggable/lib/es5/draggable.bundle.legacy.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/autosize/dist/autosize.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/chart.js/dist/Chart.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/dropzone/dist/min/dropzone.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/flatpickr/dist/flatpickr.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/highlightjs/highlight.pack.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/jquery-mask-plugin/dist/jquery.mask.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/list.js/dist/list.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/quill/dist/quill.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/select2/dist/js/select2.full.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/chart.js/Chart.extension.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/rater/rater.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/libs/image-upload/image-uploader.min.js') }}"></script>
 <!-- Map -->
 <script src='../api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>

 <!-- Theme JS -->
 <script src="{{ URL::asset('backend/assets/js/theme.min.js') }}"></script>
 <script src="{{ URL::asset('backend/assets/js/dashkit.min.js') }}"></script>

resources/views/admin/partials/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light" id="sidebar">
    <div class="container">

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarCollapse" aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Brand -->
        <a class="navbar-brand" href="{{route('user.index')}}">
            <img src="{{ asset('frontend/img/logos/logo-2.png')}}" class="navbar-brand-img
          mx-auto" alt="..."> Admin
        </a>

        <!-- User (xs) -->
        <div class="navbar-user d-md-none">

            <!-- Dropdown -->
            <div class="dropdown">

                <!-- Toggle -->
                <a href="#" id="sidebarIcon" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-sm avatar-online">
                        <img src="@if(auth()->user()->avatar) {{ auth()->user()->avatar }} @else {{ asset('backend/assets/img/avatars/profiles/avatar-1.jpg') }} @endif" class="avatar-img rounded-circle" alt="...">
                    </div>
                </a>

                <!-- Menu -->
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="sidebarIcon">
                    <a href="./profile-posts.html" class="dropdown-item">Profile</a>
                    <a href="./account-general.html" class="dropdown-item">Settings</a>
                    <hr class="dropdown-divider">
                    <a href="./sign-in.html" class="dropdown-item">Logout</a>
                </div>

            </div>

        </div>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidebarCollapse">

            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="Search" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fe fe-search"></span>
                        </div>
                    </div>
                </div>
            </form>


            <!-- Navigation -->
            <ul class="navbar-nav mb-3">

                <li class="nav-item">
                    <a class="nav-link" href="{{ url('/admin') }}">
                        <i class="fe fe-home"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('business.index') }}">
                        <i class="fe fe-briefcase"></i> Business
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('claims.index') }}">
                        <i class="fe fe-briefcase"></i> Business Claims
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('business_category.index') }}">
                        <i class="fe fe-tag"></i> Business Categories
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('city.index') }}">
                        <i class="fe fe-map-pin"></i> Cities
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('town.index') }}">
                        <i class="fe fe-map"></i> Towns
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('users.index') }}">
                        <i class="fe fe-users"></i> Users
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('subscription.index') }}">
                        <i class="fe fe-star"></i> Subscription
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('roles.index') }}">
                        <i class="fe fe-star"></i> Roles
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('permissions.index') }}">
                        <i class="fe fe-shield"></i> Permissions
                    </a>
                </li>
            </ul>





            <!-- User (md) -->
            <div class="navbar-user d-none d-md-flex" id="sidebarUser">

                <!-- Icon -->
                <a href="#sidebarModalActivity" class="navbar-user-link" data-toggle="modal">
              <span class="icon">
                <i class="fe fe-bell"></i>
              </span>
                </a>

                <!-- Dropup -->
                <div class="dropup">

                    <!-- Toggle -->
                    <a href="#" id="sidebarIconCopy" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="avatar avatar-sm avatar-online">
                            <img src="@if(auth()->user()->avatar) {{ auth()->user()->avatar }} @else {{ asset('backend/assets/img/avatars/profiles/avatar-1.jpg') }} @endif" class="avatar-img rounded-circle" alt="...">
                        </div>
                    </a>

                    <!-- Menu -->
                    <div class="dropdown-menu" aria-labelledby="sidebarIconCopy">
                        <a href="{{ route('users.edit',Auth::user()->id) }}" class="dropdown-item">Profile</a>
                        <hr class="dropdown-divider">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Logout</a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>

                </div>

                <!-- Icon -->
                <a href="#sidebarModalSearch" class="navbar-user-link" data-toggle="modal">
              <span class="icon">
                <i class="fe fe-search"></i>
              </span>
                </a>

            </div>


        </div> <!-- / .navbar-collapse -->

    </div>
</nav>